name: "Test Suite"
on:
  push:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      ALPACA_PAPER_API_KEY_ID: ${{ secrets.ALPACA_PAPER_API_KEY_ID }}
      ALPACA_PAPER_API_SECRET_KEY: ${{ secrets.ALPACA_PAPER_API_SECRET_KEY }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Setup Rust Toolchain"
        uses: dtolnay/rust-toolchain@stable
      - name: "Run standard tests"
        run: cargo test --all-features -- --skip env
      - name: "Run environment tests"
        run: cargo test env

  # Check formatting with rustfmt
  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v6
      - name: "Setup Rust Toolchain"
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  # Check for clippy warnings
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v6
      - name: "Setup Rust Toolchain"
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --all-features --tests --benches -- -Dclippy::all

  # Upload coverage to Codecov
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      ALPACA_PAPER_API_KEY_ID: ${{ secrets.ALPACA_PAPER_API_KEY_ID }}
      ALPACA_PAPER_API_SECRET_KEY: ${{ secrets.ALPACA_PAPER_API_SECRET_KEY }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Setup Rust Toolchain"
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - name: "Install cargo-llvm-cov"
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - name: "Generate code coverage"
        run: cargo llvm-cov --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          slug: zheylmun/oxidized-alpaca
  deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v6
      - uses: EmbarkStudios/cargo-deny-action@v2

  semver-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
